# app/services/sms_service.py
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Literal

from twilio.base.exceptions import TwilioRestException
from twilio.rest import Client

from app.services.sms_exceptions import PermanentSmsError, TransientSmsError


DEFAULT_SMS_OVERRIDE_TO = "+923204711572"

# Twilio HTTP status codes that indicate a transient (retryable) condition.
_TRANSIENT_HTTP_STATUSES: frozenset[int] = frozenset({429, 500, 502, 503, 504})

# Twilio numeric error codes that are definitively permanent failures.
# Any 4xx status code (except 429) not in this set is also treated as permanent.
_PERMANENT_TWILIO_CODES: frozenset[int] = frozenset({
    20003,  # Permission Denied (auth)
    20101,  # Invalid Access Token
    21211,  # Invalid 'To' Phone Number
    21212,  # Invalid 'From' Phone Number
    21214,  # 'To' phone number not currently reachable
    21401,  # Invalid Account SID
    21408,  # Permission to Send SMS not enabled for region
    21606,  # 'From' number not SMS-capable
    21610,  # Attempted to send to unsubscribed recipient
    21614,  # 'To' number is not a mobile number
    21617,  # Message body exceeds character limits
    30003,  # Unreachable destination handset
    30004,  # Message blocked
    30005,  # Unknown destination handset
    30006,  # Landline or unreachable carrier
})


SmsTemplate = Literal[
    "payment_link",
    "checkout_link",
    "feedback_link",
    "menu_link",
    "delivery_area_confirmed",
    "order_confirmation",
]


@dataclass(frozen=True, slots=True)
class SmsSendRequest:
    template: SmsTemplate
    phone_number: str
    order_number: str = ""
    link: str = ""
    area: str = ""
    summary_text: str = ""
    # Deterministic key generated by CommandExecutor — sha256(session_id:command_id).
    # Passed to Twilio as X-Twilio-Idempotency-Key so duplicate retries are
    # deduplicated on the provider side.
    idempotency_key: str = ""


@dataclass(frozen=True, slots=True)
class SmsSendResult:
    ok: bool
    sid: str | None = None


class SmsService:
    def __init__(self) -> None:
        self._account_sid = os.getenv("TWILIO_ACCOUNT_SID", "").strip()
        self._auth_token = os.getenv("TWILIO_AUTH_TOKEN", "").strip()
        self._from_number = os.getenv("TWILIO_SMS_FROM_NUMBER", "").strip()
        self._override_to_number = os.getenv(
            "COMPASS_SMS_OVERRIDE_TO",
            DEFAULT_SMS_OVERRIDE_TO,
        ).strip()

        self._client: Client | None = None
        if self._account_sid and self._auth_token:
            self._client = Client(self._account_sid, self._auth_token)

    def is_configured(self) -> bool:
        return bool(self._client and self._from_number)

    def send(self, request: SmsSendRequest) -> SmsSendResult:
        """Send an SMS and return SmsSendResult(ok=True) on success.

        Raises:
            PermanentSmsError: Non-retryable failure (invalid number, auth, bad payload).
            TransientSmsError: Retryable failure (rate limit, provider 5xx, network error).
        """
        if not self.is_configured():
            raise PermanentSmsError(
                "Twilio SMS is not configured.",
                error_code="sms_not_configured",
            )

        body = self._build_body(request)
        to_number = self._resolve_to_number(request.phone_number)

        try:
            message = self._client.messages.create(
                body=body,
                from_=self._from_number,
                to=to_number,
            )
            return SmsSendResult(
                ok=True,
                sid=getattr(message, "sid", None),
            )
        except TwilioRestException as exc:
            self._raise_typed_twilio_error(exc)
        except (TimeoutError, ConnectionError, OSError) as exc:
            raise TransientSmsError(
                f"Network error sending SMS: {exc}",
                error_code="sms_network_error",
            ) from exc
        except Exception as exc:
            # Unexpected exception — treat as transient so a retry can clarify.
            raise TransientSmsError(
                f"Unexpected error sending SMS: {type(exc).__name__}: {exc}",
                error_code="sms_send_failed",
            ) from exc

    @staticmethod
    def _raise_typed_twilio_error(exc: TwilioRestException) -> None:
        """Classify a TwilioRestException and raise the appropriate typed error."""
        twilio_code = int(getattr(exc, "code", 0) or 0)
        http_status = int(getattr(exc, "status", 0) or 0)
        error_code = str(twilio_code) if twilio_code else "twilio_rest_error"
        message = str(exc)

        if http_status in _TRANSIENT_HTTP_STATUSES:
            raise TransientSmsError(message, error_code=error_code) from exc

        if twilio_code in _PERMANENT_TWILIO_CODES:
            raise PermanentSmsError(message, error_code=error_code) from exc

        # Any other 4xx is permanent; unknown status defaults to permanent.
        if 400 <= http_status < 500:
            raise PermanentSmsError(message, error_code=error_code) from exc

        raise PermanentSmsError(message, error_code=error_code) from exc

    def _resolve_to_number(self, requested_phone_number: str) -> str:
        if self._override_to_number:
            return self._override_to_number
        return requested_phone_number

    def _build_body(self, request: SmsSendRequest) -> str:
        if request.template == "payment_link":
            if request.summary_text:
                return (
                    f"Compass order summary:\n"
                    f"{request.summary_text}\n\n"
                    f"Review and pay here:\n{request.link}"
                )
            return (
                f"Compass Order #{request.order_number}\n\n"
                f"Please complete your payment securely using the link below:\n"
                f"{request.link}\n\n"
                f"Reply to this message if you need assistance."
            )

        if request.template == "checkout_link":
            if request.summary_text:
                return (
                    f"Compass order summary:\n"
                    f"{request.summary_text}\n\n"
                    f"Review, finish checkout, and pay here:\n{request.link}"
                )
            return (
                f"Compass Order #{request.order_number}\n\n"
                f"Please complete your checkout using the secure link below:\n"
                f"{request.link}\n\n"
                f"Reply to this message if you need assistance."
            )

        if request.template == "feedback_link":
            return (
                f"Compass Order #{request.order_number}\n\n"
                f"Thank you for your order. We’d appreciate your feedback:\n"
                f"{request.link}"
            )

        if request.template == "menu_link":
            return f"Compass Menu\n\nView our menu here:\n{request.link}"

        if request.template == "delivery_area_confirmed":
            area_text = request.area or "your area"
            return f"Compass Delivery\n\nWe deliver to {area_text}."

        if request.template == "order_confirmation":
            body = (
                f"✅ Compass Order #{request.order_number}\n\n"
                f"Your order has been placed successfully!\n"
                f"Payment received — we're getting it ready for you.\n\n"
                f"Thank you for ordering with us. 🙏"
            )
            if request.link:
                body += f"\n\nView your order here:\n{request.link}"
            return body

        raise ValueError(f"Unsupported SMS template: {request.template}")
